config/routes.rb
Quasi::Application.routes.draw do
  constraints(:host => "hikultura.com") do
      match "(*x)" => redirect { |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.hikultura.com" }.to_s
      }
  end
  
  
  
  scope "(:locale)", :locale => /es|eu|fr|en/ do
    resources :followings
    resources :communications
    resources :comments
    resources :users
    resources :events
    resource :user_sessions
    resources :translations
    resources :password_resets
    resources :alarms
    resources :microposts
    resources :provinces
    
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"  
    get "sign_up" => "users#new", :as => "sign_up"

    get "add_reminder" => "reminder#add", :as => "add_reminder"
    post "del_reminder" => "reminder#delete", :as => "del_reminder"
    get "user_reminders" => "users#reminders", :as => "reminders"
    get "resubmit_event" => "events#resubmit", :as => "resubmit_event"

    get "account" => "users#microposts", :as => "account"
    
    match 'events/category/:category' => 'events#category', :as => :category
    match 'events/locations/:province' => 'events#province', :as => :province
    get 'user/profile' => 'users#profile', :as => "profile"
    get 'events_created' => 'users#events', :as =>"events_created"
    get "change_locale" => "application#change_locale", :as => "change_locale"
    get "commit_translation" => "translations#commit", :as => "commit_translation"
    get "account_locked" => "users#account_locked", :as => "account_locked"
    get "edit_password_reset" => "password_resets#edit", :as => "edit_password_reset"
    get 'alarm_switch' => "alarms#switch", :as => "alarm_switch"
    get 'cancel_event' => "events#cancel", :as => "cancel_event"
    get 'report_spam' => "comments#report_spam", :as => "report_spam"
    get "locations" => "events#locations", :as => "locations"
    match "search" => "events#search", :as => "search"
  end
 
  match '/google639a0342a2f63a68.html', 
        :to => proc { |env| [200, {}, ["google-site-verification: google639a0342a2f63a68.html"]] }
  
  match '/?locale=es' => 'events#index'
  match '/?locale=eu' => 'events#index'
  match '/?locale=fr' => 'events#index'
  match '/?locale=en' => 'events#index'
  root :to => "events#index"
  
  namespace :admin do |admin|
    resource :user_sessions
    resources :categories
    resources :events
    resources :translations
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"
    resources :users
    root :to => "user_sessions#new"
    resources :comments
    get "ban_comment" => "comments#ban_comment", :as => "ban_comment"
    get "approve_event" =>"events#approved", :as=>"approve_event"
  end
  
  
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_gmappable :check_process => false, :checker => "gmaps"
  
  belongs_to :user
  has_and_belongs_to_many :users
  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  has_many :translations, :dependent => :destroy
  has_attached_file :pic, :styles =>
            { :medium => "300x300>", :thumb => "100x100>"},
            :storage => Rails.env.production? ? :s3 : :filesystem,
            :s3_credentials => {
              :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
              :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
            },
            :path => ":attachment/:id/:style.:extension",
            :bucket => ENV['S3_BUCKET_NAME'],
            :default_url => "/images/default_:style_pic.png"
          #  :path => "for/example/:id/:style.:extension",
          #  :url  => ":s3_eu_url"

  validates_datetime :finish_date, :after => :start_date
  validates_datetime :finish_date, :on_or_after => lambda { Date.current }
  validates :town, presence: true
  validate :the_event_must_have_at_least_one_description
  scope :start_between, lambda{|from, to| where ["start_date BETWEEN ? and ?", from.to_date - 1, to.to_date + 1] }
  
  self.per_page = 10
  
  # Sets Google maps coordenates
  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.town}, #{self.province}"
  end
  
  #Sets the values for the Province select field
  PROVINCES = ["alaba", "biscay", "guipuzkoa", "navarre", "labourd", "b_navarre", "soule"]
  
  #validates the presence of at least one title and description
  def the_event_must_have_at_least_one_description
    if des_es.empty? && des_eu.empty? && des_en.empty? && des_fr.empty?
      errors.add(:des_es, "Please fill in the desciption at least in one language")
    end
    if title_es.empty? && title_eu.empty? && title_en.empty? && title_fr.empty?
      errors.add(:des_es, "Please fill in the desciption at least in one language")
    end
  end
  
  # Look for events that need to send reminders to those interested
  def self.remind_users
    @events = Event.all
    @events.each do |event|
      if (!event.reminded  && ((event.start_date-Time.now)< 259146.01469397545))
        EventNotifier.reminder(event).deliver
      end
    end
  end
  
  
  
  #validates :pic, allow_blank: true, format: {
  #    with: %r{\.(gif|jpg|png|jpeg)$}i,
  #    message: 'must be a URL for GIF, JPG or PNG image.'
  #}  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  
  after_filter :create_micropost, :only=>[:approved]
  
  def category
    @category = Category.find(params[:category])
    @events = @category.events
  end
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @comment = Comment.new(:event => @event)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
		@event = Event.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create  
    categories = params[:category_ids] or []
    @event = Event.new(params[:event].merge(:user_id => current_user.id, :category_ids => categories))

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :ok }
    end
  end
  
  def locations
  end
  
  def approved
    @event = Event.find(params[:id])
    @user = @event.user
    @content = "uploaded"
    @object=@event.id
    @event.approved = true
    @event.save
    find_alarm(@event.id)
    flash[:notice] = "Event approved succesfully"
    redirect_to admin_events_path
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  require 'will_paginate/array'
  
  
  before_filter :require_user, :only => [:new, :create, :update, :edit]
  before_filter :require_ownership, :only => [:edit, :update, :destroy]
  before_filter :set_up_events, :except =>[:locations, :province]
  before_filter :set_up_locations, :only =>[:locations, :province]
  before_filter :leftbar_on
  before_filter :leftbar_off, :only =>[:index, :category, :province, :locations]
  after_filter :create_micropost, :only=>[:update]
  require 'date'
  
  
  #Method in that processes the queries from the search box
  def search
    @events = Event.where((["CAST(town as varchar(255)) LIKE ?", "%#{params[:search_where]}%"]))
    @events = @events.where((["CAST(title_es as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_en as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_eu as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_fr as varchar(255)) LIKE ?", "%#{params[:query]}%"]) )

    @time = Time.new(params[:search_start_date][:year], params[:search_start_date][:month],params[:search_start_date][:day] , params[:search_start_date][:hour], params[:search_start_date][:minute])
    @events = @events.where("start_date >= ?", @time)
    
    #titles and place done
    
    categories = params[:category_ids].map(&:to_i) rescue []
    
    @events = @events.select do |event| 
      categories.any?{|c| event.category_ids.include? c }
    end
    
    #categories done
    
    @events = Array.wrap(@events.paginate(:page=>params[:page]))
  end
  
  # Filters events by category
  def category
    @category = Category.find(params[:category])
    @events = @category.events.paginate(:page => params[:page])
    meta :title => @category.name, :description => @category.name
  end
  
  # Display all the events
  def index
    #@events = Event.paginate(:page => params[:page])
    #@events = Event.paginate(:page => params[:page], :order=> 'start_date ASC')
    @events = Event.where('finish_date >= ?', Time.now).where('approved = ?', true).order('start_date ASC').paginate(:page => params[:page])
  end


  # Display an event
  def show
    @event = Event.find(params[:id])
    @event.views = @event.views + 1
    #@event.save
    @comment = Comment.new(:event => @event)
    @json = @event.to_gmaps4rails
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end


  # Create a new instane of event
  def new
		@event = Event.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # Edits an event
  def edit
    @event = Event.find(params[:id])
  end


  # Creates and saves a new event
  def create  
    categories = params[:category_ids] or []
    @event = Event.new(params[:event].merge(:user_id => current_user.id, :category_ids => categories))
    check_date
    respond_to do |format|
      if @event.save
        AdminMailer.approve_event(@event).deliver
        format.html { redirect_to @event, notice: I18n.t(:events_create) }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # Updates event's parameters after being edited
  def update
    categories = params[:category_ids] or []
    @event = Event.find(params[:id])
    @user = @event.user
    @object = @event.id
    
    if @event.cancelled
      @content = "cancelled"
      @event.approved = true
      respond_to do |format|
        if @event.update_attributes(params[:event].merge(:category_ids => categories))
          format.html { redirect_to events_created_path, notice: I18n.t(:event_deleted) }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
      EventNotifier.cancellation(@event).deliver
    else
      if @event.approved?
        @content = "edited"
      end  
      check_date
      respond_to do |format|
        if @event.update_attributes(params[:event].merge(:category_ids => categories))
          format.html { redirect_to events_created_path, notice: I18n.t(:event_update) }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
  end
  
  # Creates a new event with same parameters of an existing one
  def resubmit
    @old_event = Event.find(params[:id])
    @event = Event.new
  end
  
  

  # Deletes an event
  def destroy
    @event = Event.find(params[:id])
    if (@event.users.empty? || (@event.approved =false))
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :ok }
      end
    else
      @event.cancelled = true
      @event.approved = false
      @event.save
      redirect_to cancel_event_path(:id=>@event.id)
    end
  end
  
  # Cancels an event
  def cancel
    @event = Event.find(params[:id])
  end
  
  def locations
    @events =Event.paginate(:page => params[:page])
  end
  
  # Filters events by province
  def province
    @province = params[:province]
    @events = Event.where(:province => @province).paginate(:page => params[:page])
  end
  
  # Checks whether a comment has been posted more than 5 min ago
  def deletable_comment
    @comment = Comment.find(params[:id])
    if Time.now > (@comment.created_at + 5.minutes)
      flash[:notice] = "This comment is already in memory system and cannot be deleted"
      redirect_to @comment.event
      return false
    end
  end
  
  
  
private
  # Set the event to 'reminded'
  def check_date
    if close_date
      @event.reminded = true
    end
  end
  
  # Checks whether an event is happening in less than 72h
  def close_date
    if ((@event.start_date-Time.now)< 259146.01469397545)
      true
    else 
      false
    end
  end
 
  # Sets the variables for the events menu tab
  def set_up_events
    set_up('events')
  end
  
  # Sets the variable for the locations menu tab
  def set_up_locations
    set_up('locations')
  end
  
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_comment.html.haml
.comment
  %strong
    - usr = h comment.user.name
    = link_to usr, comment.user
    says:
  %br/
  %small
    Posted #{time_ago_in_words(comment.created_at)} ago
  %em= simple_format h(comment.body)
  = link_to 'Destroy Comment', comment,                   
    :confirm => 'Are you sure?',                          
    :method => :delete  
  -if comment.banned.eql?(false)
    = link_to "Ban Comment", admin_ban_comment_path(:id => comment.id) 
  -else 
    %strong Already Banned

app/views/admin/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
    = f.text_field :title
  
  Categories
  - Category.all.each do |category|
    .field
      = check_box_tag "category_ids[]", category.id
      = category.name
      
    
  .field
    = f.label :start_date
    %br
    = f.datetime_select :start_date
  .field
    = f.label :finish_date
    %br
    = f.datetime_select :finish_date
  .field
    = f.label :place
    %br
    = f.text_field :place
  .field
    = f.label :town
    %br
    = f.text_field :town
  .field
    = f.label :province
    %br
    = f.text_field :province
  .field
    = f.label :price
    %br
    = f.text_field :price
  .field
    = f.label :description
    %br
    = f.text_area :description
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :website
    %br
    = f.text_field :website
  .field
    = f.label :phone
    %br
    = f.text_field :phone
  %p
    %b Picture
    %br
    = f.file_field :pic
  .actions
    = f.submit

app/views/admin/events/category.html.haml
%p#notice= notice

%h1
  All events with category
  = @category.name

%table
  - @events.each do |event|
    %tr{:class => cycle('list_line_odd', 'list_line_even')}
      %td
        - pic = image_tag(event.pic.url(:thumb), class: 'list_image')
        = link_to pic, event
      %td.list_description
        %dl
          %dt= link_to event.title, event
          %dd= l event.start_date, :format => :long
          %dd
            = event.place
            | #{event.town}
          %dd= truncate(strip_tags(event.description), length:80)
%br/

app/views/admin/events/edit.html.haml
%p#notice= notice
%h1 Editing event
= render 'form'

link_to 'Back', admin_events_path

app/views/admin/events/index.html.haml
%p#notice= notice
%table
  - @events.each do |event|
    %tr{:class => cycle('list_line_odd', 'list_line_even')}
      %td
        - pic = image_tag(event.pic.url(:thumb), class: 'list_image')
        = link_to pic, admin_event_path(event)
      %td.list_description
        %dl
          -@event = event
          %dt= link_to (render "layouts/title"), admin_event_path(event)
          %dd= l event.start_date, :format => :long
          %dd
            = event.place
            | #{event.town}
          = link_to 'Edit', edit_admin_event_path(event)
          = link_to 'Destroy', admin_event_path(event), confirm: 'Are you sure?', method: :delete
          %strong
            -if !event.approved?
              = link_to "Approve!", admin_approve_event_path(:id =>event.id)
%br

app/views/admin/events/locations.html.haml
%p#notice= notice
%h4 Working on it...

app/views/admin/events/new.html.haml
%p#notice= notice
%h1 New event
= render 'form'

app/views/admin/events/show.html.haml
%p#notice= notice
#main.top
  %div
    = image_tag(@event.pic.url(:medium), class:"list_image_show")
  %p
    %h2= @event.title
  .details
    %p
      %b Starts:
      = l @event.start_date, :format => :long
    %p
      %b Finishes:
      = l @event.finish_date, :format => :long
    %p
      %b Place:
      = @event.place
    %p
      %b Town:
      = @event.town
      %b Province:
      = @event.province
    %p
      %b Price:
      €#{@event.price}
    %p
      %b Categories:
      = @event.categories.map(&:name).to_sentence

#info
  .side_big
    #description
      %p
        %b Description:
        = @event.description
      %p
        %b Mail:
        = @event.email
      %p
        %b Website:
        = @event.website
      %p
        %b Phone:
        = @event.phone
      %p
        %b Created by:
        = link_to @event.user.name, @event.user
    #comments
      #comments_count= pluralize(@event.comments.count, 'comment')
      #new_comment
        = form_for @comment do|f|
          = f.hidden_field :event_id
          %p
            = f.label :Coment!
            %br/
            = f.text_area :body
          %p
            = f.submit "Post Comment"
      #all_comments
        = render :partial => 'comment', :collection => @event.comments
  .side_small
    
    .attenders
      = @event.users.size
      interested!
      %div
        - @event.users.each do |user_id|
          - @user = User.find(user_id)
          %p
            - userName = @user.name
          %br/
          - user_pic= image_tag(@user.photo.url(:thumb), class:"side_pic")
          = link_to user_pic, @user
          = link_to userName, @user
          
= link_to 'Edit', edit_admin_event_path(@event)
= link_to 'Back', admin_events_path