config/routes.rb
Quasi::Application.routes.draw do
  constraints(:host => "hikultura.com") do
      match "(*x)" => redirect { |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.hikultura.com" }.to_s
      }
  end
  
  
  
  scope "(:locale)", :locale => /es|eu|fr|en/ do
    resources :followings
    resources :communications
    resources :comments
    resources :users
    resources :events
    resource :user_sessions
    resources :translations
    resources :password_resets
    resources :alarms
    resources :microposts
    resources :provinces
    
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"  
    get "sign_up" => "users#new", :as => "sign_up"

    get "add_reminder" => "reminder#add", :as => "add_reminder"
    post "del_reminder" => "reminder#delete", :as => "del_reminder"
    get "user_reminders" => "users#reminders", :as => "reminders"
    get "resubmit_event" => "events#resubmit", :as => "resubmit_event"

    get "account" => "users#microposts", :as => "account"
    
    match 'events/category/:category' => 'events#category', :as => :category
    match 'events/locations/:province' => 'events#province', :as => :province
    get 'user/profile' => 'users#profile', :as => "profile"
    get 'events_created' => 'users#events', :as =>"events_created"
    get "change_locale" => "application#change_locale", :as => "change_locale"
    get "commit_translation" => "translations#commit", :as => "commit_translation"
    get "account_locked" => "users#account_locked", :as => "account_locked"
    get "edit_password_reset" => "password_resets#edit", :as => "edit_password_reset"
    get 'alarm_switch' => "alarms#switch", :as => "alarm_switch"
    get 'cancel_event' => "events#cancel", :as => "cancel_event"
    get 'report_spam' => "comments#report_spam", :as => "report_spam"
    get "locations" => "events#locations", :as => "locations"
    match "search" => "events#search", :as => "search"
  end
 
  match '/google639a0342a2f63a68.html', 
        :to => proc { |env| [200, {}, ["google-site-verification: google639a0342a2f63a68.html"]] }
  
  match '/?locale=es' => 'events#index'
  match '/?locale=eu' => 'events#index'
  match '/?locale=fr' => 'events#index'
  match '/?locale=en' => 'events#index'
  root :to => "events#index"
  
  namespace :admin do |admin|
    resource :user_sessions
    resources :categories
    resources :events
    resources :translations
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"
    resources :users
    root :to => "user_sessions#new"
    resources :comments
    get "ban_comment" => "comments#ban_comment", :as => "ban_comment"
    get "approve_event" =>"events#approved", :as=>"approve_event"
  end
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  validates_presence_of :email
  validates_presence_of :name
  has_and_belongs_to_many :events
  has_many :created_events, :class_name => "Event", :foreign_key => "user_id"
  has_many :comments, :dependent => :destroy
  
  has_attached_file :photo, :styles => 
     { :medium => "300x300>", :thumb => "100x100>"},
      :storage => Rails.env.production? ? :s3 : :filesystem,
      :s3_credentials => {
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
      },
      :path => ":attachment/:id/:style.:extension",
      :bucket => ENV['S3_BUCKET_NAME'],
      :default_url => "/images/default_:style_photo.png"
      
    #{ :medium => "300x300>", :thumb => "100x100>" }
    #,
    #:storage => Rails.env.production? ? :s3 : :filesystem,
    #:s3_credentials => { :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']},
    #:s3_protocol => "https",
    #:path => ":class/:id/:basename_:style.:extension",
    #:path => ":attachment/:id/:style.:extension",
    #:bucket => ENV['S3_BUCKET_NAME']
    #:url  => ":s3_eu_url"
  
  has_many :followings, :dependent => :destroy
  has_many :followeds, :through => :followings, :dependent => :destroy
  has_many :communications
  has_many :receivers, :through => :communications
  has_many :translations, :dependent => :destroy
  has_many :alarms, :dependent => :destroy
  has_many :microposts, :dependent => :destroy
   
  self.per_page = 10
  
  #Sets the values for the Province select field 
  PROVINCES = ["alaba", "biscay", "guipuzkoa", "navarre", "labourd", "b_navarre", "soule"] 
  
  # Call the email service to email the user the reset password instructions
  def deliver_password_reset_instructions!
    reset_perishable_token!
    AccountNotifier.password_reset_instructions(self).deliver
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  # GET /users
  # GET /users.json
  def index
    @events = Event.order(:title)
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = Event.order(:title)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @events = Event.order(:start_date)
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.events_created = [ ]
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @events = Event.order(:title)
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
  
  def reminders
    @events = Event.order(:title)
     @user = current_user
  end
  
  def events
    @events = Event.order(:start_date)
    @user = current_user
  end
  
  def messages
    @events = Event.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter {set_up('account')}
  before_filter :require_user, :only =>[:edit, :update, :destroy, :reminders, :messages, :events, :microposts, :profile]
  before_filter :get_current_user, :only => [:edit, :update, :destroy, :reminders, :events, :messages, :microposts, :profile]
  before_filter :leftbar_on
  
  # Gets all the users interested in an event
  def index
    @event = Event.find(params[:id])
    @users = @event.users
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end


  # Shows the public view of a user profile
  def show
    @user = User.find(params[:id])
    @followers = Following.where(:followed_id => @user).all
    meta :title => @user.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end


  # Creates a new instance of user
  def new
    @user = User.new
  end

  # Edits an existing suer
  def edit
  end


  # Creates and saves a new user
  def create
    @user = User.new(params[:user])
    @user.locale = I18n.locale
    AccountNotifier.confirm(@user).deliver
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: I18n.t(:users_create) }
        format.json { render json: @user, status: :created, location: @user }
        
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # Updates an existing user's parameters after being edited
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: I18n.t(:users_update) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # Deletes a user from the database
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
  
  # Displays the reminders of a user
  def reminders
  @events = @user.events.where('finish_date >= ?', Time.now).paginate(:page => params[:page])
    #@events = @even.find(:all, :conditions=> ['finish_date >= ?', Time.now])
  #@events = @user.events.paginate(:page =>params[:page])
  end
  
  # Displays the created events of a user
  def events
    @even = @user.created_events.order('created_at DESC')
    @events = @even.paginate(:page => params[:page])
  end
  
  # Displays the messages of a user
  def messages
  end

  # Displays a use the status of account locked
  def account_locked
    @user = User.find(params[:id])
  end
  
  # Displays the followed's microposts of a user
  def microposts   
    @microposts = Micropost.where(user_id: current_user.followed_ids).order('created_at desc').all
  end
  
  # Displays the private view of a user profile
  def profile
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        =t :user_form_error
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label t :user_name
    %br
    = f.text_field :name
  .field
    = f.label t :user_email
    %br
    = f.email_field :email
  .field
    = f.label t :user_town
    %br
    = f.text_field :town
  .field
    = f.label t :user_province
    %br
    = select(:user, :province, User::PROVINCES.collect {|d| [I18n.t(d), d]})
  .field
    = f.label t :user_website
    %br
    = f.text_field :website
  .field
    = f.label t :user_photo
    %br
    = f.file_field :photo
  .actions
    = f.submit

app/views/users/account_locked.html.haml
%h2.capital.theFont
  =title I18n.t(:account_locked)
%p
  In order to prevent possible attacks your
  account has been locked and is waiting for verification.
%p
  Follow this link =>
  %b=link_to "to reset your password", new_password_reset_path
  

app/views/users/edit.html.haml
%h2.capital.theFont
  =title I18n.t(:edit_user)
= render 'form'
= link_to I18n.t(:show), @user

app/views/users/events.html.haml
%h2.capital.theFont
  =title I18n.t(:user_events_created)
%div
  - if @events.empty?
    %p 
    =t :user_no_events_created
  - else
    - @events.each do |event|
      #user_block
        #user_block_pic
          = image_tag(event.pic.url(:medium), class: 'user_event_block_image', :alt =>'Event Picture')
        #user_block_details{:style=>"width:53%;"}
          .user_event_title.capital
            %b 
              -@event=event
              =truncate(strip_tags(render 'layouts/title'), length:28)
          %div
            %d
              =l event.start_date, :format=> :long
          %div
            =event.place
            %d.capital
              =event.town
          %div.red_font
            -if !event.translations.empty? 
              -event.translations.each do |translation| 
                %small
                  %i
                    =link_to I18n.t(:translation_pending), translation
        #user_block_info
          - if !event.cancelled && event.finish_date >= Time.now
            %div.rotate_div{:style=>"font-size:95%; background-color:#8c8c8c;"}
              .rotate_text.capital.line_height
                =link_to I18n.t(:edit), edit_event_path(event)
            %div.rotate_div{:style=>"background-color:black;"}
              .rotate_text.capital.line_height
                =link_to I18n.t(:cancel), event, confirm: I18n.t(:are_you_sure), method: :delete
          %div.rotate_div
            .rotate_text.line_height
              =link_to 'INFO', event
          %div.rotate_div{:style=>"background-color:#404041;"}
            .rotate_text.capital.line_height
              =link_to I18n.t(:submit_similar), resubmit_event_path(:id => event.id)

-if @events.count > 10
  #pagination
    .apple_pagination
      = will_paginate @events

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th 
      =t :user_name
    %th 
      =t :user_town
    %th
      =t :user_province
    %th
      =t :user_photo

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.town
      %td= user.province
      %td
        - image = image_tag(@user.photo.url(:thumb), class: 'list_image')
        = link_to image, @user
%br

app/views/users/messages.html.haml
%h3 Messages

-if @user.communications.empty?
  No communication established so far...
-else
  - for communication in @user.communications
    %p 
      ()-------------------
      =link_to communication.user.name, ""
      =link_to communication.body, ""

app/views/users/microposts.html.haml
%h2.capital.theFont
  =title I18n.t(:recent_activity)

-if @user.followings.empty?
  %p
    Here you can keep up to date checking the activity of the users you are following.
%p
-@microposts.each do |micro|
  #micropost_entry
    =link_to micro.user.name, micro.user, :class=>'capital', :style=>'color:#404041;'
    =I18n.t(micro.content)
    -if micro.content.eql?("following")
      -if !User.exists?(:id=>micro.object_id)
        =t :user_nil
      -else
        -@user = User.find(micro.object_id)
        =link_to @user.name, @user, :class=>'capital', :style=>'color:#8c8c8c;'
    -else
      -if !Event.exists?(:id=>micro.object_id)
        =t :event_nil
      -else
        -@event = Event.find(micro.object_id)
        -title = render 'layouts/title'
        =link_to title, @event, :class=>'capital', :style=>'color:red;'
    %br
    %i
      =t :comment_posted  
      #{time_ago_in_words(micro.created_at)}
  

app/views/users/new.html.haml
%h1
  =title I18n.t(:sign_up) 


= form_for @user, { :multipart => true } do |f|
  - if @user.errors.any?
    .error_messages
      %h2
        =t :user_form_error
      %ul
        - for message in @user.errors.full_messages
          %li= message
  = f.hidden_field :town
  = f.hidden_field :province
  = f.hidden_field :website
  %p
    = f.label t :user_name
    %br
    = f.text_field :name
  %p
    = f.label t :user_email
    %br
    = f.email_field :email
  %p
    = f.label t :user_password
    %br
    = f.password_field :password
  %p
    = f.label t :user_password_confirmation
    %br
    = f.password_field :password_confirmation
  %p
    = f.label t :user_photo
    %br
    = f.file_field :photo
  
  %p.button= f.submit

app/views/users/profile.html.haml
%h2.capital.theFont
  =title I18n.t(:profile)
 
#profile_header.capital.theFont{:style=>'font-size:150%:'}
  =title @user.name

#profile_info
  #profile_pic
    - user_picture = image_tag(@user.photo.url(:medium), :alt=>'Picture of your profile')
    = link_to user_picture, @user.photo.url(:original), :id=>'single_image'
  #profile_options.capital
    %div{:style=>"background-color:#8c8c8c;"}
      = link_to I18n.t(:edit), edit_user_path(@user)
    %div{:style=>"background-color:black;"}
      = link_to I18n.t(:delete), admin_user_path(@user), confirm: I18n.t(:are_you_sure), method: :delete

#profile_details
  %div
    %b.user_field.capital
      = t :user_town
    %br/
    = @user.town
  %div
    %b.user_field.capital
      = t :user_province
    %br/
    = I18n.t(@user.province) if !@user.province.empty?
  %div
    %b.user_field.capital
      = t :user_website
    %br/
    = @user.website
  %div
    %b.user_field.capital
      = t :email
    %br/
    = @user.email

app/views/users/reminders.html.haml
%h2.capital.theFont
  =title I18n.t(:user_reminders)
%div
  %div
    - if @events.empty?
      %p 
        = t :user_no_reminders
    - else
      -@events.each do |event|
        #user_block
          #user_block_pic
            = image_tag(event.pic.url(:medium), class: 'user_event_block_image', :alt =>'Event Picture')
          #user_block_details{:style=>"width:61%;"}
            .user_event_title.capital
              %b 
                -@event=event
                =truncate(strip_tags(render 'layouts/title'), length:32)
                
            %div
              %d
                =l event.start_date, :format=> :long
            %div
              =event.place
              %d.capital
                =event.town
          #user_block_info
            %div.rotate_div
              .rotate_text.line_height
                =link_to 'INFO', event
            %div.rotate_div{:style=>"background-color:black;"}
              .rotate_text.capital.line_height
                =link_to I18n.t(:delete), del_reminder_path(:id => event.id), confirm: I18n.t(:are_you_sure), method: del_reminder_path(:id => event.id)

-if @events.count > 10
  #pagination
    .apple_pagination
      = will_paginate @events

app/views/users/show.html.haml
%h2.capital.theFont
  =title @user.name

#profile_info
  #profile_pic{:style=>'width:100%;'}
    - user_picture = image_tag(@user.photo.url(:medium), :alt=>'Picture of your profile')
    = link_to user_picture, @user.photo.url(:original), :id=>'single_image'


#profile_details
  %div
    %b.user_field.capital
      = t :user_town
    %br/
    = @user.town
  %div
    %b.user_field.capital
      = t :user_province
    %br/
    = I18n.t(@user.province) if !@user.province.empty?
  %div
    %b.user_field.capital
      = t :user_website
    %br/
    = @user.website
  %div

    
#profile_follow_user
  %p
    -if !@user.eql?(current_user)
      -if (current_user && current_user.followings.any?{|follow| follow.followed_id == @user.id})
        =t :user_already_following
      -else  
        .capital
          = link_to I18n.t(:follow_button), followings_path(:followed_id => @user.id), :method => :post   
        
#profile_user_followings
  %div
    %b.capital
      Followings
    %br/
    -if @user.followings.empty?
      %p
        =t :user_no_follows
    -else
      -for following in @user.followings
        %p
          -user_name=following.followed.name
          -user_photo = image_tag(following.followed.photo.url(:thumb),alt:"Following Picture")
          =link_to user_photo, following.followed
          .capital{:style=>'margin-top:-10px'}
            =link_to user_name, following.followed
  %div
    %b.capital
      Followers
    %br/
    -if @followers.empty?
      %p
        =t :user_no_followers
    -else
      -@followers.each do |follow|
        - @follower = User.find(follow.user_id)
        %p
          -userName = @follower.name
          -user_photo = image_tag(@follower.photo.url(:thumb), alt:"Followed Pciture")
          =link_to user_photo, @follower
          .capital{:style=>'margin-top:-10px'}
            =link_to userName, @follower 