config/routes.rb
Quasi::Application.routes.draw do
  constraints(:host => "hikultura.com") do
      match "(*x)" => redirect { |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.hikultura.com" }.to_s
      }
  end
  
  
  
  scope "(:locale)", :locale => /es|eu|fr|en/ do
    resources :followings
    resources :communications
    resources :comments
    resources :users
    resources :events
    resource :user_sessions
    resources :translations
    resources :password_resets
    resources :alarms
    resources :microposts
    resources :provinces
    
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"  
    get "sign_up" => "users#new", :as => "sign_up"

    get "add_reminder" => "reminder#add", :as => "add_reminder"
    post "del_reminder" => "reminder#delete", :as => "del_reminder"
    get "user_reminders" => "users#reminders", :as => "reminders"
    get "resubmit_event" => "events#resubmit", :as => "resubmit_event"

    get "account" => "users#microposts", :as => "account"
    
    match 'events/category/:category' => 'events#category', :as => :category
    match 'events/locations/:province' => 'events#province', :as => :province
    get 'user/profile' => 'users#profile', :as => "profile"
    get 'events_created' => 'users#events', :as =>"events_created"
    get "change_locale" => "application#change_locale", :as => "change_locale"
    get "commit_translation" => "translations#commit", :as => "commit_translation"
    get "account_locked" => "users#account_locked", :as => "account_locked"
    get "edit_password_reset" => "password_resets#edit", :as => "edit_password_reset"
    get 'alarm_switch' => "alarms#switch", :as => "alarm_switch"
    get 'cancel_event' => "events#cancel", :as => "cancel_event"
    get 'report_spam' => "comments#report_spam", :as => "report_spam"
    get "locations" => "events#locations", :as => "locations"
    match "search" => "events#search", :as => "search"
  end
 
  match '/google639a0342a2f63a68.html', 
        :to => proc { |env| [200, {}, ["google-site-verification: google639a0342a2f63a68.html"]] }
  
  match '/?locale=es' => 'events#index'
  match '/?locale=eu' => 'events#index'
  match '/?locale=fr' => 'events#index'
  match '/?locale=en' => 'events#index'
  root :to => "events#index"
  
  namespace :admin do |admin|
    resource :user_sessions
    resources :categories
    resources :events
    resources :translations
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"
    resources :users
    root :to => "user_sessions#new"
    resources :comments
    get "ban_comment" => "comments#ban_comment", :as => "ban_comment"
    get "approve_event" =>"events#approved", :as=>"approve_event"
  end
  
  
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_gmappable :check_process => false, :checker => "gmaps"
  
  belongs_to :user
  has_and_belongs_to_many :users
  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  has_many :translations, :dependent => :destroy
  has_attached_file :pic, :styles =>
            { :medium => "300x300>", :thumb => "100x100>"},
            :storage => Rails.env.production? ? :s3 : :filesystem,
            :s3_credentials => {
              :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
              :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
            },
            :path => ":attachment/:id/:style.:extension",
            :bucket => ENV['S3_BUCKET_NAME'],
            :default_url => "/images/default_:style_pic.png"
          #  :path => "for/example/:id/:style.:extension",
          #  :url  => ":s3_eu_url"

  validates_datetime :finish_date, :after => :start_date
  validates_datetime :finish_date, :on_or_after => lambda { Date.current }
  validates :town, presence: true
  validate :the_event_must_have_at_least_one_description
  scope :start_between, lambda{|from, to| where ["start_date BETWEEN ? and ?", from.to_date - 1, to.to_date + 1] }
  
  self.per_page = 10
  
  # Sets Google maps coordenates
  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.town}, #{self.province}"
  end
  
  #Sets the values for the Province select field
  PROVINCES = ["alaba", "biscay", "guipuzkoa", "navarre", "labourd", "b_navarre", "soule"]
  
  #validates the presence of at least one title and description
  def the_event_must_have_at_least_one_description
    if des_es.empty? && des_eu.empty? && des_en.empty? && des_fr.empty?
      errors.add(:des_es, "Please fill in the desciption at least in one language")
    end
    if title_es.empty? && title_eu.empty? && title_en.empty? && title_fr.empty?
      errors.add(:des_es, "Please fill in the desciption at least in one language")
    end
  end
  
  # Look for events that need to send reminders to those interested
  def self.remind_users
    @events = Event.all
    @events.each do |event|
      if (!event.reminded  && ((event.start_date-Time.now)< 259146.01469397545))
        EventNotifier.reminder(event).deliver
      end
    end
  end
  
  
  
  #validates :pic, allow_blank: true, format: {
  #    with: %r{\.(gif|jpg|png|jpeg)$}i,
  #    message: 'must be a URL for GIF, JPG or PNG image.'
  #}  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  
  after_filter :create_micropost, :only=>[:approved]
  
  def category
    @category = Category.find(params[:category])
    @events = @category.events
  end
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @comment = Comment.new(:event => @event)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
		@event = Event.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create  
    categories = params[:category_ids] or []
    @event = Event.new(params[:event].merge(:user_id => current_user.id, :category_ids => categories))

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :ok }
    end
  end
  
  def locations
  end
  
  def approved
    @event = Event.find(params[:id])
    @user = @event.user
    @content = "uploaded"
    @object=@event.id
    @event.approved = true
    @event.save
    find_alarm(@event.id)
    flash[:notice] = "Event approved succesfully"
    redirect_to admin_events_path
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  require 'will_paginate/array'
  
  
  before_filter :require_user, :only => [:new, :create, :update, :edit]
  before_filter :require_ownership, :only => [:edit, :update, :destroy]
  before_filter :set_up_events, :except =>[:locations, :province]
  before_filter :set_up_locations, :only =>[:locations, :province]
  before_filter :leftbar_on
  before_filter :leftbar_off, :only =>[:index, :category, :province, :locations]
  after_filter :create_micropost, :only=>[:update]
  require 'date'
  
  
  #Method in that processes the queries from the search box
  def search
    @events = Event.where((["CAST(town as varchar(255)) LIKE ?", "%#{params[:search_where]}%"]))
    @events = @events.where((["CAST(title_es as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_en as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_eu as varchar(255)) LIKE ?", "%#{params[:query]}%"] && ["CAST(title_fr as varchar(255)) LIKE ?", "%#{params[:query]}%"]) )

    @time = Time.new(params[:search_start_date][:year], params[:search_start_date][:month],params[:search_start_date][:day] , params[:search_start_date][:hour], params[:search_start_date][:minute])
    @events = @events.where("start_date >= ?", @time)
    
    #titles and place done
    
    categories = params[:category_ids].map(&:to_i) rescue []
    
    @events = @events.select do |event| 
      categories.any?{|c| event.category_ids.include? c }
    end
    
    #categories done
    
    @events = Array.wrap(@events.paginate(:page=>params[:page]))
  end
  
  # Filters events by category
  def category
    @category = Category.find(params[:category])
    @events = @category.events.paginate(:page => params[:page])
    meta :title => @category.name, :description => @category.name
  end
  
  # Display all the events
  def index
    #@events = Event.paginate(:page => params[:page])
    #@events = Event.paginate(:page => params[:page], :order=> 'start_date ASC')
    @events = Event.where('finish_date >= ?', Time.now).where('approved = ?', true).order('start_date ASC').paginate(:page => params[:page])
  end


  # Display an event
  def show
    @event = Event.find(params[:id])
    @event.views = @event.views + 1
    #@event.save
    @comment = Comment.new(:event => @event)
    @json = @event.to_gmaps4rails
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end


  # Create a new instane of event
  def new
		@event = Event.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # Edits an event
  def edit
    @event = Event.find(params[:id])
  end


  # Creates and saves a new event
  def create  
    categories = params[:category_ids] or []
    @event = Event.new(params[:event].merge(:user_id => current_user.id, :category_ids => categories))
    check_date
    respond_to do |format|
      if @event.save
        AdminMailer.approve_event(@event).deliver
        format.html { redirect_to @event, notice: I18n.t(:events_create) }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # Updates event's parameters after being edited
  def update
    categories = params[:category_ids] or []
    @event = Event.find(params[:id])
    @user = @event.user
    @object = @event.id
    
    if @event.cancelled
      @content = "cancelled"
      @event.approved = true
      respond_to do |format|
        if @event.update_attributes(params[:event].merge(:category_ids => categories))
          format.html { redirect_to events_created_path, notice: I18n.t(:event_deleted) }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
      EventNotifier.cancellation(@event).deliver
    else
      if @event.approved?
        @content = "edited"
      end  
      check_date
      respond_to do |format|
        if @event.update_attributes(params[:event].merge(:category_ids => categories))
          format.html { redirect_to events_created_path, notice: I18n.t(:event_update) }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
  end
  
  # Creates a new event with same parameters of an existing one
  def resubmit
    @old_event = Event.find(params[:id])
    @event = Event.new
  end
  
  

  # Deletes an event
  def destroy
    @event = Event.find(params[:id])
    if (@event.users.empty? || (@event.approved =false))
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :ok }
      end
    else
      @event.cancelled = true
      @event.approved = false
      @event.save
      redirect_to cancel_event_path(:id=>@event.id)
    end
  end
  
  # Cancels an event
  def cancel
    @event = Event.find(params[:id])
  end
  
  def locations
    @events =Event.paginate(:page => params[:page])
  end
  
  # Filters events by province
  def province
    @province = params[:province]
    @events = Event.where(:province => @province).paginate(:page => params[:page])
  end
  
  # Checks whether a comment has been posted more than 5 min ago
  def deletable_comment
    @comment = Comment.find(params[:id])
    if Time.now > (@comment.created_at + 5.minutes)
      flash[:notice] = "This comment is already in memory system and cannot be deleted"
      redirect_to @comment.event
      return false
    end
  end
  
  
  
private
  # Set the event to 'reminded'
  def check_date
    if close_date
      @event.reminded = true
    end
  end
  
  # Checks whether an event is happening in less than 72h
  def close_date
    if ((@event.start_date-Time.now)< 259146.01469397545)
      true
    else 
      false
    end
  end
 
  # Sets the variables for the events menu tab
  def set_up_events
    set_up('events')
  end
  
  # Sets the variable for the locations menu tab
  def set_up_locations
    set_up('locations')
  end
  
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_comment.html.haml
#comment
  #comment_user_photo
    =link_to image_tag(comment.user.photo.url(:thumb), class:'comment_user_photo', :alt=>"user photo"), comment.user
    %br/
    =t :comment_posted  
    #{time_ago_in_words(comment.created_at)}
  #comment_body
    %strong
      - usr = h comment.user.name
      = link_to usr, comment.user
    %i
      = t :comment_says
    %br/
    -if comment.banned?
      %em 
        %small
          = simple_format t :comment_banned
    -else
      %h3= simple_format h(comment.body)
  #comment_options
    -if !comment.banned?
      =link_to image_tag("spam_culture_basque_country.gif", class:'comment_options_icon'), report_spam_path(:id =>comment.id), :confirm => "Do you want to report this comment as spam or inappropriate?"
    -if Time.now < (comment.created_at + 5.minutes)
      = link_to image_tag("delete_basque_culture.png", class:'comment_options_icon'), comment,                   
        :confirm => I18n.t(:are_you_sure),                          
        :method => :delete if current_user.eql?(comment.user)

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        =t :event_form_error
        //prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
          
          
  #tabs 
    -if I18n.locale.to_s=="en" 
      %ul
        %li
          =link_to I18n.t(:lang_english), '#tabs-4'
        %li
          =link_to I18n.t(:lang_spanish), '#tabs-1'
        %li
          =link_to I18n.t(:lang_basque), '#tabs-2'
        %li
          =link_to I18n.t(:lang_french), '#tabs-3'
    -elsif I18n.locale.to_s=="eu" 
      %ul
        %li
          =link_to I18n.t(:lang_basque), '#tabs-2'
        %li
          =link_to I18n.t(:lang_spanish), '#tabs-1'
        %li
          =link_to I18n.t(:lang_french), '#tabs-3'
        %li
          =link_to I18n.t(:lang_english), '#tabs-4'
    -elsif I18n.locale.to_s=="fr" 
      %ul
        %li
          =link_to I18n.t(:lang_french), '#tabs-3'
        %li
          =link_to I18n.t(:lang_basque), '#tabs-2'
        %li
          =link_to I18n.t(:lang_spanish), '#tabs-1'
        %li
          =link_to I18n.t(:lang_english), '#tabs-4'
    -else
      %ul
        %li
          =link_to I18n.t(:lang_spanish), '#tabs-1'
        %li
          =link_to I18n.t(:lang_basque), '#tabs-2'
        %li
          =link_to I18n.t(:lang_french), '#tabs-3'
        %li
          =link_to I18n.t(:lang_english), '#tabs-4'
  
    #tabs-1
      %p
        .field
          = f.label "Titulo del Evento"
          = f.text_field :title_es, :class=>"total_width"
        %br
        .field
          = f.label "Descripcion del Evento"
          %br
          = f.text_area :des_es, :rows => 15, :class=>"total_width"
    #tabs-2
      %p
        .field
          = f.label "Ekitaldiaren Titulua"
          = f.text_field :title_eu, :class=>"total_width"
        %br
        .field
          = f.label "Ekitaldiaren Deskripzioa"
          %br
          = f.text_area :des_eu, :rows => 15, :class=>"total_width"
    #tabs-3
      %p
        .field
          = f.label "Titre de L'événement"
          = f.text_field :title_fr, :class=>"total_width"
        %br
        .field
          = f.label "Descripcion de L'événement"
          %br
          = f.text_area :des_fr, :rows => 15, :class=>"total_width"
    #tabs-4
      %p
        .field
          = f.label "Event Title"
          = f.text_field :title_en, :class=>"total_width"
        %br
        .field
          = f.label "Event Description"
          %br
          = f.text_area :des_en, :rows => 15, :class=>"total_width"
        
        
        
  
  = f.label t :event_categories
  - Category.all.each do |category|
    .field
      = check_box_tag "category_ids[]", category.id, @event.category_ids.include?(category.id)
      = I18n.t("categories.#{category.name}")
  
  .field
    = f.label t :event_start_date
    %br
    = f.datetime_select :start_date
  .field
    = f.label t :event_finish_date
    %br
    = f.datetime_select :finish_date
  .field
    = f.label t :event_place
    %br
    = f.text_field :place
  .field
    = f.label t :event_address
    %br
    = f.text_field :address
  .field
    = f.label t :event_town
    %br
    = f.text_field :town
  .field
    = f.label t :event_province
    %br
    = select(:event, :province, Event::PROVINCES.collect {|d| [I18n.t(d), d]})
    
  .field
    = f.label t :event_price
    %br
    = f.number_field :price

  .field
    = f.label t :email
    %br
    = f.email_field :email
  .field
    = f.label t :event_website
    %br
    = f.text_field :website
  .field
    = f.label t :event_phone
    %br
    = f.telephone_field :phone
  .field
    = f.label :Tickets_Online
    %br
    = f.telephone_field :tickets
  %p
    = f.label t :event_pic
    %br
    = f.file_field :pic
  .actions
    = f.submit

app/views/events/_search.html.haml
%h1.out
  -title 'Goazen'
#search
  -@events.each do |event|
    #user_block
      #user_block_pic
        -pic= image_tag(event.pic.url(:medium), class: 'event_block_image', :alt =>'Event Picture')
        =link_to pic, event
      #user_block_details{:style=>"width:66%;"}
        .event_title.capital
          %b 
            -@event=event
            =truncate(strip_tags(render 'layouts/title'), length:30)
        %div
          %d
            =l event.start_date, :format=> :block
          %d.event_town
            =truncate(strip_tags(event.place), length:10)
          %d.capital
            =event.town
        %p
          %small
            =truncate(strip_tags(render 'layouts/description'), length:320)
      #block_info
        .rotate_text
          =link_to 'INFO', event
        
  -if @events.count > 11
    #pagination
      .apple_pagination
        = will_paginate @events

app/views/events/cancel.html.haml
%h2.capital.theFont
  =title I18n.t(:event_cancelation)
%p
  =t :cancel_intro
  
%p

  
= form_for(@event) do |f|  
  .field
    = f.label t :cancel_message
    %br
    = f.text_area :cancel_message
  .actions
    =f.submit

app/views/events/category.html.haml
%h1.out
  -title I18n.t(:events_in_cat)+" "+I18n.t("categories.#{@category.name}")
  

-@events.each do |event|
  #block
    #block_pic
      -pic = image_tag(event.pic.url(:medium), class: 'event_block_image', :alt =>'Event Picture')
      =link_to pic, event
    #block_details
      .event_title.capital
        %b 
          -@event=event
          =render 'layouts/title'
      %div
        %d
          =l event.start_date, :format=> :block
        %d.event_town
          =event.place
        %d.capital
          =event.town
      %p
        %small
          =truncate(strip_tags(render 'layouts/description'), length:320)
    #block_info
      .rotate_text
        =link_to 'INFO', event
        
-if @events.count > 11
  #pagination
    .apple_pagination
      = will_paginate @events

app/views/events/edit.html.haml
%h2.capital.theFont
  =title I18n.t(:edit_event)
= render 'form'
= link_to I18n.t(:show), @event
|
\#{link_to 'Back', events_path}

app/views/events/index.html.haml
%h1.out
  =title I18n.t(:slogan)

-@events.each do |event|
  #block
    #block_pic
      -pic = image_tag(event.pic.url(:medium), class: 'event_block_image', :alt =>'Event Picture')
      =link_to pic, event
    #block_details
      .event_title.capital
        %b 
          -@event=event
          =render 'layouts/title'
      %div
        %d
          =l event.start_date, :format=> :block
        %d.event_town
          =event.place
        %d.capital
          =event.town
      %p
        %small
          =truncate(strip_tags(render 'layouts/description'), length:320)
    #block_info
      .rotate_text
        =link_to 'INFO', event
        
-if @events.count > 11
  #pagination
    .apple_pagination
      = will_paginate @events

app/views/events/locations.html.haml
%h1.out
  -title I18n.t(:locations)
-@events.each do |event|
  #block
    #block_pic
      -pic = image_tag(event.pic.url(:medium), class: 'event_block_image', :alt =>'Event Picture')
      =link_to pic, event
    #block_details
      .event_title.capital
        %b 
          -@event=event
          =render 'layouts/title'
      %div
        %d
          =l event.start_date, :format=> :block
        %d.event_town
          =event.place
        %d.capital
          =event.town
      %p
        %small
          =truncate(strip_tags(render 'layouts/description'), length:320)
    #block_info
      .rotate_text
        =link_to 'INFO', event
#pagination
  .apple_pagination
    = will_paginate

app/views/events/new.html.haml
%h2.capital.theFont
  =title I18n.t(:new_event)
= render 'form'

app/views/events/province.html.haml
%h1.out
  -title I18n.t(:events_in) +" " + I18n.t(@province)
  

-@events.each do |event|
  #block
    #block_pic
      -pic = image_tag(event.pic.url(:medium), class: 'event_block_image', :alt =>'Event Picture')
      =link_to pic, event
    #block_details
      .event_title.capital
        %b 
          -@event=event
          =render 'layouts/title'
      %div
        %d
          =l event.start_date, :format=> :block
        %d.event_town
          =event.place
        %d.capital
          =event.town
      %p
        %small
          =truncate(strip_tags(render 'layouts/description'), length:320)
    #block_info
      .rotate_text
        =link_to 'INFO', event
        
-if @events.count > 11
  #pagination
    .apple_pagination
      = will_paginate @events

app/views/events/search.js.erb
$('#central').html("<%= escape_javascript( render(:partial => 'search') ) %>");  //ajax return of search results
$('#left_bar').html("<%= escape_javascript( render(:partial => 'layouts/left_bar') ) %>");  //ajax for left bar when returning search results

app/views/events/show.html.haml
-meta :title => (render "layouts/title"), :description =>(truncate(strip_tags(render 'layouts/description'), length:250))
#central_with_bar
  #photo
    %center
      - event_photo= image_tag(@event.pic.url(:original), class:"event_show_photo", :alt =>"Event picture")
      =link_to event_photo, @event.pic.url(:original), :id=>'single_image'
  #main_details
    #title.capital.red_font.width_total
      %h1
        
        =title render "layouts/title"
    %div.width_half
      %b.capital.red_font.width_total 
        = t :event_dates
      %br/
      = l @event.start_date, :format => :long
      %br/
      = l @event.finish_date, :format => :long
    %div.width_half
      %b.capital.red_font.width_total 
        = t :event_price
      %br/
      - if @event.price.nil?
        n/a
      -else
        #{@event.price}€
    %div.width_half
      %b.capital.red_font.width_total 
        = t :event_place 
      %br/
      = @event.place
      %d.capital
        = @event.town
    %div.width_half
      %b.capital.red_font.width_total 
        = t :event_categories
      %br/
      =@event.categories.map{|category| I18n.t("categories.#{category.name}")}.to_sentence
  
  #event_description
    =simple_format(render 'layouts/description')
      
  #event_reminder
    %div
      -if @event.finish_date > Time.now
        -if @event.cancelled?
          %h2.capital{:style=>"color:red;"} This event has been cancelled
        -else
          -if (current_user && current_user.events.include?(@event))
            %h4  
              -if ((@event.start_date-Time.now)< 259146.01469397545)
                =t :reminder_soon
              -else
                = t :already_following_event
          -else
            -if I18n.locale.to_s =="es"
              .sp_remind
                =link_to 'remind_me', add_reminder_path(:id => @event.id)   
            
            -else I18n.locale.to_s=="en"
              .en_remind
                =link_to 'remind_me', add_reminder_path(:id => @event.id)   
            
          -if I18n.locale.to_s =="es"
            .sp_translate
              =link_to I18n.t('add_translation'), new_translation_path(:id => @event.id)
          -else I18n.locale.to_s=="en"
            .en_translate
              =link_to I18n.t('add_translation'), new_translation_path(:id => @event.id)
  #tabs
    %ul
      %li
        =link_to I18n.t("comment", :count=> @event.comments.count), '#tabs-1', :id=>'comments_count'
      %li
        =link_to I18n.t("interested", :count=> @event.users.count), '#tabs-2'
      %li
        =link_to "Event Info", '#tabs-3'
      %li
        =link_to "Map", '#tabs-4'
    
    #tabs-1
      #new_comment
        #new_comment_form
          = form_for @comment do|f|
            = f.hidden_field :event_id
            %p
              %h3
                = f.label t :do_comment
              %br/
              = f.text_area(:body, :class=>"comment_box")
            %p
              = f.submit t :submit_comment
        #new_comment_user_photo
          -if current_user
            =image_tag(current_user.photo.url(:thumb))
      #all_comments
        = render :partial => 'comment', :collection => @event.comments.order('created_at DESC')
    #tabs-2
      #attenders
        - @event.users.each do |user|
          #an_attender
            #an_attender_photo
              =link_to image_tag(user.photo.url(:thumb), class:"side_pic"), user
            #an_attender_info
              %h3= link_to user.name, user
              =user.town
              %br/
              =user.province
              
              
              
    #tabs-3
      #event_contact_info
        %p
          %b.capital.red_font 
            =t :email
          %br/
          = @event.email
        %p
          %b.capital.red_font
            =t :event_website
          %br/
          = link_to @event.website, @event.website
        %p
          %b.capital.red_font 
            = t :event_phone
          %br/
          = @event.phone
        %p
          %b.capital.red_font
            tickets
          %br/
          = link_to @event.tickets, @event.tickets
        %p
      #event_contact_photo
        %b.capital.red_font 
          =t :event_creator
        -unless @event.user.nil?
          =@event.user.name
          =link_to image_tag(@event.user.photo.url(:thumb)), @event.user
          
    
    #tabs-4
      #gmap
        =gmaps("map_options" => { "detect_location" => true, "auto_zoom" => false, "center_on_user" => true, "zoom" => 17},"markers" => { "data" => @json })
        
      
    



    


  