config/routes.rb
Quasi::Application.routes.draw do
  constraints(:host => "hikultura.com") do
      match "(*x)" => redirect { |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.hikultura.com" }.to_s
      }
  end
  
  
  
  scope "(:locale)", :locale => /es|eu|fr|en/ do
    resources :followings
    resources :communications
    resources :comments
    resources :users
    resources :events
    resource :user_sessions
    resources :translations
    resources :password_resets
    resources :alarms
    resources :microposts
    resources :provinces
    
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"  
    get "sign_up" => "users#new", :as => "sign_up"

    get "add_reminder" => "reminder#add", :as => "add_reminder"
    post "del_reminder" => "reminder#delete", :as => "del_reminder"
    get "user_reminders" => "users#reminders", :as => "reminders"
    get "resubmit_event" => "events#resubmit", :as => "resubmit_event"

    get "account" => "users#microposts", :as => "account"
    
    match 'events/category/:category' => 'events#category', :as => :category
    match 'events/locations/:province' => 'events#province', :as => :province
    get 'user/profile' => 'users#profile', :as => "profile"
    get 'events_created' => 'users#events', :as =>"events_created"
    get "change_locale" => "application#change_locale", :as => "change_locale"
    get "commit_translation" => "translations#commit", :as => "commit_translation"
    get "account_locked" => "users#account_locked", :as => "account_locked"
    get "edit_password_reset" => "password_resets#edit", :as => "edit_password_reset"
    get 'alarm_switch' => "alarms#switch", :as => "alarm_switch"
    get 'cancel_event' => "events#cancel", :as => "cancel_event"
    get 'report_spam' => "comments#report_spam", :as => "report_spam"
    get "locations" => "events#locations", :as => "locations"
    match "search" => "events#search", :as => "search"
  end
 
  match '/google639a0342a2f63a68.html', 
        :to => proc { |env| [200, {}, ["google-site-verification: google639a0342a2f63a68.html"]] }
  
  match '/?locale=es' => 'events#index'
  match '/?locale=eu' => 'events#index'
  match '/?locale=fr' => 'events#index'
  match '/?locale=en' => 'events#index'
  root :to => "events#index"
  
  namespace :admin do |admin|
    resource :user_sessions
    resources :categories
    resources :events
    resources :translations
    get "log_in" => "user_sessions#new", :as => "log_in"
    get "log_out" => "user_sessions#destroy", :as => "log_out"
    resources :users
    root :to => "user_sessions#new"
    resources :comments
    get "ban_comment" => "comments#ban_comment", :as => "ban_comment"
    get "approve_event" =>"events#approved", :as=>"approve_event"
  end
  
  
  
  

end

app/views/admin/layouts/_title.html.haml
-if I18n.locale.to_s == "en" && !@event.title_en.empty?
  =@event.title_en
-elsif I18n.locale.to_s == "eu" && !@event.title_eu.empty?
  = @event.title_eu
-elsif I18n.locale.to_s == "fr" && !@event.title_fr.empty?
  = @event.title_fr
-elsif !@event.title_es.empty?
  =@event.title_es
-elsif !@event.title_eu.empty?
  = @event.title_eu
-elsif !@event.title_fr.empty?
  =@event.title_fr
-else
  = @event.title_en

app/views/admin/layouts/application.html.haml
!!!
%html
  %head
    %title The best web - - version 0.0.8.1.5.2 Beta
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
  %body{:class => "#{controller.controller_name} container"}
    .container
      #header
        %header
          = yield :head
          .wrap
            #logo
              - logo_tag = image_tag("eguzkilore.png", :alt => "Logo")
              = link_to logo_tag, root_path
            #right
              #loggin
                - flash.each do |name, msg|
                  = content_tag :div, msg, :id => "flash#{name}"
                #user_nav
                  - if current_user
                    Logged in as #{current_user.name}
                    = link_to I18n.t(:log_out), log_out_path
                  - else
                    = link_to I18n.t(:sign_up), sign_up_path
                    = t :o_word
                    = link_to I18n.t(:log_in), log_in_path
                #lang.ln
                  %li= link_to "eu ", change_locale_path(:locale => "eu")
                  %li= link_to "es", change_locale_path(:locale => "es")
                  %li= link_to "en", change_locale_path(:locale => "en")
                  %li= link_to "fr", change_locale_path(:locale => "fr")
              #bottom
                #banner
                #menu
                  %nav
                    %ul
                      %li= link_to_unless_current I18n.t(:menu_events), ""
                      %li= link_to_unless_current I18n.t(:menu_locations), locations_path
                      %li= link_to_unless_current I18n.t(:menu_account), account_path
                #search
                  %h4 Search:
      #main
        #sidebar
          %sidebar
            #searchBox
              %p
                =t :search_keyword
                %input#event_title.blockShadow{:name => "titleinput", :size => "20", :type => "text", :value => ""}/
              %p
                =t :search_when
                %input#event_title.blockShadow{:name => "titleinput", :size => "19", :type => "text", :value => ""}/
              %p
                =t :search_categories
                %input#event_title.blockShadow{:name => "titleinput", :size => "20", :type => "list", :value => ""}/
              %p
                =t :search_where
                %input#event_title.blockShadow{:name => "titleinput", :size => "20", :type => "date_select", :value => "", :placeholder => I18n.t(:search_placeholder_where)}/
              %p ---------------------------------------
              #sButton
                %li= link_to "Crack on!", root_path
            #uploadEvent
              = link_to I18n.t(:upload_event_button), new_event_path, :class => "upload_button", :alt => "Subir evento"
        #submenu
          %div
            %b= link_to "All", events_path
          - @categories.each do |category|
            %div
              %b= link_to category.name, category_path(category)
              
        
        #right_side
          = yield
      #footer
        =yield :scripts